// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7_TpbOZNJk6Z1pWI5cSDVIxiioRjBWV8',
    appId: '1:531891096536:web:87028a0fda90d1aad880ad',
    messagingSenderId: '531891096536',
    projectId: 'travelapp-31255',
    authDomain: 'travelapp-31255.firebaseapp.com',
    storageBucket: 'travelapp-31255.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeiu539Qs6-V2Hsc4h-Zby5ARu3OkBX6w',
    appId: '1:531891096536:android:d15391c4766a4ea7d880ad',
    messagingSenderId: '531891096536',
    projectId: 'travelapp-31255',
    storageBucket: 'travelapp-31255.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf8lc2QQiw63rzEJtl3ev82boDpPmgS7s',
    appId: '1:531891096536:ios:34641153670335add880ad',
    messagingSenderId: '531891096536',
    projectId: 'travelapp-31255',
    storageBucket: 'travelapp-31255.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf8lc2QQiw63rzEJtl3ev82boDpPmgS7s',
    appId: '1:531891096536:ios:34641153670335add880ad',
    messagingSenderId: '531891096536',
    projectId: 'travelapp-31255',
    storageBucket: 'travelapp-31255.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7_TpbOZNJk6Z1pWI5cSDVIxiioRjBWV8',
    appId: '1:531891096536:web:e0b7a17ad2edb379d880ad',
    messagingSenderId: '531891096536',
    projectId: 'travelapp-31255',
    authDomain: 'travelapp-31255.firebaseapp.com',
    storageBucket: 'travelapp-31255.firebasestorage.app',
  );
}
